on: pull_request

name: Check

jobs:
  fmt:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - run: make fmt

  vet:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - run: make vet

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - run: make test
